services:
  records-api:
    build:
      context: ./records-api
      dockerfile: Dockerfile
    container_name: records-api
    volumes:
      - ./records-api:/var/www/html
    env_file:
      - ./records-api/.env
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - ./records-api:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - records-api
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: records-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
